name: stack_appodeal_flutter
description: Official flutter plugin to support Appodeal SDK for Android and iOS platforms. Support Consent Dialog for GDPR/CCPA zone.
version: 1.2.1
homepage: https://www.appodeal.com

environment:
  sdk: ">=2.12.0 <3.0.0"
  flutter: ">=1.20.0"

dependencies:
  flutter:
    sdk: flutter

dev_dependencies:
  flutter_test:
    sdk: flutter

flutter:
  plugin:
    platforms:
      android:
        package: com.appodeal.appodeal_flutter
        pluginClass: AppodealFlutterPlugin
      ios:
        pluginClass: AppodealFlutterPlugin